package com.hxs.dynamo.data.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.validation.constraints.NotEmpty;

/**
 * @author HSteidel
 */
@DynamoDBTable(tableName = "AnalyticEvents")
public class AnalyticEvent {

    private String id;

    @NotEmpty
    private String brand;

    @NotEmpty
    private String channel;

    @NotEmpty
    private String filename;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getBrand() {
        return brand;
    }

    @DynamoDBAttribute
    public String getChannel() {
        return channel;
    }

    @DynamoDBAttribute
    public String getFilename() {
        return filename;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }
}
